name: Github CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up python 3.13.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.13.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check linting
      - name: Run tests
